# Generated by Django 3.2 on 2023-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0036_notify_is_delete_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Register'), (2, 'Register call code'), (3, 'Feeback'), (4, 'Example 1'), (5, 'Example 2'), (6, 'TestEvent'), (7, 'Mailing list')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Register'), (2, 'Register call code'), (3, 'Feeback'), (4, 'Example 1'), (5, 'Example 2'), (6, 'TestEvent'), (7, 'Mailing list')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='systemnotify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Register'), (2, 'Register call code'), (3, 'Feeback'), (4, 'Example 1'), (5, 'Example 2'), (6, 'TestEvent'), (7, 'Mailing list')], null=True, verbose_name='Событие'),
        ),
    ]
